### ISSUE TITLE
Not working, stuck at loading

### ISSUE THREAD

**Issue by OmarShawky1** [dflock/ulauncher-window-switcher#11]
![image](https://user-images.githubusercontent.com/51538094/144716404-ea0268ab-1258-4250-9fad-0ea085ad713b.png)

OS: Elementary OS 5.1.7 Hera based on Ubuntu 18.04 LTS using Pantheon Desktop.

Error from terminal log
```
2021-12-04 18:09:44,873 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 1 results
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/api/client/Client.py", line 54, in on_message
    self.extension.trigger_event(event)
  File "/usr/lib/python3/dist-packages/ulauncher/api/client/Extension.py", line 52, in trigger_event
    action = listener.on_event(event, self)
  File "/home/omar/.local/share/ulauncher/extensions/com.github.dflock.ulauncher-window-switcher/main.py", line 80, in on_event
    window["ws"], ws_dict[window["ws"]], w_idx
KeyError: 0
com.github.dflock.ulauncher-window-switcher | 2021-12-04 18:09:44,874 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event KeywordQueryEvent

```

**Comment by dflock** [comment]
Could you post the output from the following commands please?

```console
$ python --version
```

and 

```console
$ wmctrl -l | awk '{ if( $2 != "-1") { $3="";  print $0} }'
```

and 

```console
$ wmctrl -d | sed -n -E -e 's/^.*WA: (N\/A|.,. [[:digit:]]+x[[:digit:]]+)  //p'
```

Thanks!

**Comment by OmarShawky1** [comment]
```
$ $ python --version
Python 2.7.17
```
0x01a00003 0  wingpanel
0x06800008 0  program-langs-part-a - Discord
0x04a00016 0  Warm & Cozy November Jazz - Relax Coffee Time Jazz For Study, Work, Stress Relief - Jazz BGM - YouTube
0x04a00017 0  Not working, stuck at loading · Issue #11 · dflock/ulauncher-window-switcher - Google Chrome
0x0360000a 0  wmctrl -l
stuck at loading (Issue #11)
```
$ wmctrl -l | awk '{ if( $2 != "-1") { $3="";  print $0} }'
0x01a00003 0  wingpanel
0x06800008 0  program-langs-part-a - Discord
0x04a00016 0  Warm & Cozy November Jazz - Relax Coffee Time Jazz For Study, Work, Stress Relief - Jazz BGM - YouTube
0x04a00017 0  Not working, stuck at loading · Issue #11 · dflock/ulauncher-window-switcher - Google Chrome
0x0360000a 0  wmctrl -l
0x04800007 0  Mailspring · Re: [dflock/ulauncher-window-switcher] Not working, stuck at loading (Issue #11)
```

```
$ wmctrl -d | sed -n -E -e 's/^.*WA: (N\/A|.,. [[:digit:]]+x[[:digit:]]+)  //p'
```

**Comment by dflock** [comment]
Fantastic, thanks!

Sorry, I forgot one:

```console
$ python3 --version
```

**Comment by OmarShawky1** [comment]
```
$ python3 --version
Python 3.6.9
```

**Comment by vipranarayan14** [comment]
I also get the same error.

OS: elementary OS 6 Odin

```
$ python --version
Python 3.10.0
```

```
$ python3 --version
Python 3.10.0
```

```
$ wmctrl -l | awk '{ if( $2 != "-1") { $3="";  print $0} }'
0x01e00003 0  io.elementary.wingpanel
0x05a00007 0  /home/user/Documents/Data
0x04000001 0  v3.md - Visual Studio Code
0x0540002b 1  Not working, stuck at loading · Issue #11 · dflock/ulauncher-window-switcher — Mozilla Firefox
0x0580004a 1  Synaptic Package Manager
0x028001ec 0  Ulauncher Preferences
```
```
$ wmctrl -d | sed -n -E -e 's/^.*WA: (N\/A|.,. [[:digit:]]+x[[:digit:]]+)  //p'
```

**Comment by dflock** [comment]
I have just pushed a change which fixes one instance of getting suck at "Loading..." which I found. Maybe this fixes it for you?

**Comment by OmarShawky1** [comment]
Nope.

**Comment by dflock** [comment]
It seems like this command doesn't work on elementaryOS, for some reason:

```console
$ wmctrl -d | sed -n -E -e 's/^.*WA: (N\/A|.,. [[:digit:]]+x[[:digit:]]+)  //p'
```

This should spit out a list of workspace names, something like this:

```console
$ wmctrl -d | sed -n -E -e 's/^.*WA: (N\/A|.,. [[:digit:]]+x[[:digit:]]+)  //p'

Personal: Email
Notes
Todo
Finances
Project: duncanlock.net
Personal: D&D
Project: Nim
[empty]
Project: dotfiles
[empty]
Project: antora-default-ui
Project: Home Dashboard
Project: LanguageTool
Project: Gemini
Project: lite-xl
Project: Standard eBooks
Project: NAS & Storage
Project: Processing
Personal: Retro Hardware
Project: ulauncher
[empty]
[empty]
[empty]
Music
```

If running that doesn't produce any output, can you please just try this command on its own:

```console
$ wmctrl -d
```

and paste the output from that?

**Comment by OmarShawky1** [comment]
I have 2 screens and 2 workspaces which add up to 3.

```
$ wmctrl -d
0  * DG: 2640x1024  VP: 0,0  WA: 0,30 2640x994  Workspace 1
1  - DG: 2640x1024  VP: N/A  WA: 0,30 2640x994  Workspace 2
2  - DG: 2640x1024  VP: N/A  WA: 0,30 2640x994  Workspace 3
```

Edit:
[This](https://askubuntu.com/questions/23427/how-can-i-get-a-list-of-all-open-windows-in-the-command-line) solution appears to be working, it uses `wmctrrl -l` instead if `d` flag
Here is the output sample:
```
$ wmctrl -l
0x01c00003 -1 omar-LLaptop plank
0x02e00003 -1 omar-LLaptop 
0x02e0007d -1 omar-LLaptop HTC
0x06200001  1 omar-LLaptop hw7.sml - Programming-Languages-Course - Visual Studio Code
0x05e00006  0 omar-LLaptop Barrier
0x07400003  1 omar-LLaptop hw7.pdf - Personal - Microsoft​ Edge
0x01a00003  0 omar-LLaptop wingpanel
0x0ae00002  0 omar-LLaptop Spotify
0x07200088  0 omar-LLaptop How can I get a list of all open windows in the command line? - Ask Ubuntu - Google Chrome
0x0aa0000a  0 omar-LLaptop wmctrl -l

```

**Comment by authmane512** [comment]
I have the same problem on Linux Mint 20.3 Xfce

**Comment by stefanjarina** [comment]
Hi,

fix here is fairly easy, posted pull request #12 

In the meantime before author merges pull request, you can check if it works for you by editing the line `62` in
`$HOME/.local/share/ulauncher/extensions/com.github.dflock.ulauncher-window-switcher/main.py`

```diff
result = subprocess.run(
            [
-                 "wmctrl -d | sed -n -E -e 's/^.*WA: (N\/A|.,. [[:digit:]]+x[[:digit:]]+)  //p'"
+                 "wmctrl -d | sed -n -E -e 's/^.*WA: (N\/A|.+,.+ [[:digit:]]+x[[:digit:]]+)  //p'"
            ],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,  # equivalent to capture_output=True
            shell=True,
            universal_newlines=True,  # equivalent to text=True
        ).stdout
```

For me it now works flawlessly:
![image](https://user-images.githubusercontent.com/2995233/165494540-44a4fe56-fd31-4a02-bef3-1a77a1858281.png)

**Comment by OmarShawky1** [comment]
@stefanjarina Yes, This solved the entire problem & it worked smooth. Thank you.

**Comment by matheusunderline** [comment]
Wow, awesome, thank you so much to fix this useful plugin! ❤️
